Repository hpc-io/pdc, pull requests merged in 2023-10, with the labels that each got.

#144 Compile parallel tests only when PDC_ENABLE_MPI is ON
  src/tests/CMakeLists.txt
Labels: type: bug, priority:high

#135 Remove copy of Spack recipe
  spack/package.py
Labels: priority:low

#145 Include GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/install_problem.md
  .github/ISSUE_TEMPLATE/question.md
  .github/pull_request_template.md
Labels: priority:medium
