Repository hpc-io/pdc, pull requests merged in 2025-04, with the labels that each got.

#243 use latest cmake in CI
  .github/workflows/dependencies-linux.sh
  .github/workflows/ubuntu-cache.yml
  .github/workflows/ubuntu-no-cache.yaml
Labels: type: CI

#245 Add `pdc_logger.h` to installation
  src/commons/CMakeLists.txt
Labels: type: bug

#228 Fix restart issue
  src/server/pdc_server.c
Labels: type: bug

#250 Fix printing in `PGOTO_ERROR` and `PGOTO_ERROR_VOID`
  src/commons/utils/include/pdc_private.h
Labels: type: enhancement
